In [1]:
# for installing the numpy 
!pip install numpy

#import numpy module with alias np
import numpy as np


In [2]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
h = np.array([1,2,3,4,'h'])
# print h
h

array(['1', '2', '3', '4', 'h'], dtype='<U21')

#Dimensions in Arrays

In [3]:
#define a,b,c and d as instructed above

a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
#print dimentions of a,b, c and d
print('a dimension:', a.ndim)
print('b dimension:', b.ndim)
print('c dimension:', c.ndim)
print('d dimension:', d.ndim)

#print there shape as well,using shape attribute
# print shape of each a,b ,c and d
print(a)
print('shape of a:', a.shape)
print(b)
print('shape of b:', b.shape)
print(c)
print('shape of c:', c.shape)
print(d)
print('shape of d:', d.shape)

#check data type using dtype attribute
# print data type of c and d
print(c.dtype)
print(d.dtype)

#check numpy variable use type() function
#print type of a and b variable
print(type(a))
print(type(b))
# Lets check length of array b, using len() function
len(d)

a dimension: 0
b dimension: 1
c dimension: 2
d dimension: 3
10
shape of a: ()
[1 2 3]
shape of b: (3,)
[[1 2 3]
 [4 5 6]]
shape of c: (2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
shape of d: (2, 2, 3)
int64
int64
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


2

Creating Numpy array


In [4]:
#Create a numpy array using arange with 1 and 11 as parameter in it
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Create an array using arange passing 1,11 and 2 as parameters
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
# create numpy array using eye function with 3 as passed parameter
np.eye(2, dtype = float) 

array([[1., 0.],
       [0., 1.]])

In [7]:
#create a numpy array using zero function with (3,2) as passed parameter takes default float
np.zeros((3, 5),dtype='int') # default float


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [8]:
#create a numpy array using ones function with (3,2) as passed parameter
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
#create a numpy array using full function with (3,2) and 2 as passed parameter
np.full((2, 3), 111,dtype=int)

array([[111, 111, 111],
       [111, 111, 111]])

In [10]:
#create a numpy array using diag function passing a list [1,2,3,4,5]
x = [1,2,3,4,5,6,7]
np.diag(x)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

Numpy Reshape

In [11]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [12]:
# Reshape x with 2 rows and 8 columns
n=x.reshape((8,2)) # 1d
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
(8, 2)
2


In [13]:
n1=n.reshape((4,2,2))
print(n1)
print(n1.shape)
print(n1.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3


In [14]:
# convert to old dimension
v=n.ravel()
print(v.shape)
print(v)
print(v.ndim)

(16,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1


In [15]:
# reshape x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
print(x)
x.reshape((2,8))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

NumPy Array Indexing

In [16]:
# Flattening x convert array into one dimensional
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [17]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2,17,2)

# print a
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [18]:
# Get third element in array a
a[2]

np.int64(6)

In [19]:
#Print 3rd, 5th, and 7th element in array a
a[0:7:2]

array([ 2,  6, 10, 14])

In [20]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# print the 3rd element from the 3rd row of a
a[2,2]

np.int64(9)

In [22]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b.shape
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.
b[1][1][2]

np.int64(12)

NumPy Array Slicing

In [24]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Slice elements from 1st to 5th element from array arr:
arr[0:5]


array([1, 2, 3, 4, 5])

In [26]:
# Slice elements from index 5 to the end of the array arr:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [27]:
# Slice elements from the beginning to index 5 (not included) in array arr:
arr[0:5]

array([1, 2, 3, 4, 5])

In [28]:
# Print every other element from index 1 to index 7:
arr[1:7:2]

array([2, 4, 6])

In [29]:
# Return every other element from the entire array arr:
arr[0:10:2]

array([1, 3, 5, 7, 9])

In [30]:
# Print array a
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# In array 'a' print index 2 from all the rows :
arr[2]

np.int64(3)

In [32]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
a[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

Numpy copy vs view

In [33]:
x1= np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# assign x2 = x1
x2 = x1 # view 

In [35]:
#print x1 and x2
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [36]:
# change 1st element of x2 as 10
x2[0] = 10

In [37]:
#Again print x1 and x2
print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [38]:
print(id(x1))
print(id(x2))

2379976248848
2379976248848


In [39]:
# Check memory share between x1 and x2
print(np.shares_memory(x1, x2))
print(id(x1))
print(id(x2))

True
2379976248848
2379976248848


In [40]:
# Create a view of x1 and store it in x3.
x3 = x1.view()

In [41]:
# Again check memory share between x1 and x3
np.shares_memory(x1, x3)

True

In [42]:
#Change 1st element of x3=100
x3[0] = 100

In [43]:
#print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


In [44]:
# Now create an array x4 which is copy of x1
x4 = np.copy(x1)

In [45]:
# Change the last element of x4 as 900
x4[-1] = 900

In [46]:
# print both x1 and x4 to check if changes reflected in both
print(x1)
print(x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


In [47]:
#Check memory share between x1 and x4
print(id(x1))
print(id(x4))
np.shares_memory(x1, x4)

2379976248848
2379976248272


False

Operations on Numpy

In [48]:
#print a
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
# Check if every element in array a greater than 3 or not Using '>' notation
a > 3


array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [50]:
# Get a list with all elements of array 'a' grater than 3
a[a > 3]

array([4, 5, 6, 7, 8, 9])

In [51]:
# Get a list with all elements of array 'a' greater than 3 but less than 6
a[(a > 3) & (a < 6)]

array([4, 5])

In [52]:
# check if each elements in array 'x1' equals array 'x4' using '==' notation
x1 == x4
# print(x1)
# print(x4)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [53]:
# Print Transpose of array 'a'
print(a.transpose())
#print array 'a'
print("-----------------")
print(a) 

[[1 4 7]
 [2 5 8]
 [3 6 9]]
-----------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
# stack x1 and x4 along columns.
print(x1)
print(x4)
np.vstack((x1, x4))

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100,   1,   2,   3,   4,   5,   6,   7,   8, 900]])

In [55]:
#stack x1 and x4 along rows
np.hstack((x1, x4))

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,   1,   2,
         3,   4,   5,   6,   7,   8, 900])

Adding, Insert and delete Numpy array

In [56]:
# Inserts values into array x1 before index 4 with elements of x4
print(x1)
print(x4)
np.insert(x1, 4, x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([100,   1,   2,   3, 100,   1,   2,   3,   4,   5,   6,   7,   8,
       900,   4,   5,   6,   7,   8,   9])

In [57]:
# delete 2nd element from array x2
print(x2)
np.delete(x2, 0)

[100   1   2   3   4   5   6   7   8   9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Mathmatical operations on Numpy array

In [58]:
#defining a
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [59]:
# print trigonometric sin value of each element of a
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [60]:
(np.sin(a))/(np.cos(a))

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [61]:
# print trigonometric cos value of each element of a
print(np.cos(a))
print(np.tan(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [62]:
# Print exponential value of each elements of a
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [63]:
# print total sum of elements of a
np.sum(a)

np.int64(45)

In [64]:
# Print sum in array a column wise
np.sum(a, axis=1)

array([ 6, 15, 24])

In [65]:
# Print sum in array a row wise
np.sum(a, axis=0)

array([12, 15, 18])

In [66]:
# print median of array a
np.median(a)

np.float64(5.0)

In [67]:
# print mean of array a
np.mean(a)


np.float64(5.0)

In [68]:
# print standard deviation of array a
np.std(a)

np.float64(2.581988897471611)

In [69]:
#print largest element present in array a
np.max(a)

np.int64(9)

In [70]:
# print sorted x4 array
np.sort(x4)

array([  1,   2,   3,   4,   5,   6,   7,   8, 100, 900])

Searching Arrays

In [71]:
# print the indexes where the value is 4 in array x1
m=np.where(x1 == 4)
m

(array([4]),)

In [72]:
#print array x1
x1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [73]:
c=np.array([44,55,66,88,99,12,12,12,12,12,10,10,10,101,0])

In [74]:
# Print the indexes where the values are even in array x1
np.where(c%2 == 0)


(array([ 0,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 14]),)

In [75]:
# Print x1 where x1 is greater than 5, also if number is less than 5 then replace it with 0
np.where(x1>5, x1, 0)

array([100,   0,   0,   0,   0,   0,   6,   7,   8,   9])

In [76]:
print(dir(list))

print(dir(set))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', 